#!/bin/sh

#$ -S /bin/bash
#$ -cwd
#$ -e ./dist/
#$ -o ./dist/
#$ -V

DATASET="test/fixtures/final*.txt"

echo "$ mpi82"
OMP_NUM_THREADS=8 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=8 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=8 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
echo "$ ---"

echo "$ mpiX2"
OMP_NUM_THREADS=20 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=20 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=20 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
