#!/bin/sh

#$ -S /bin/bash
#$ -cwd
#$ -e ./dist/
#$ -o ./dist/
#$ -V

DATASET="test/fixtures/kun10.txt"

echo "$ mpi162 t!"
OMP_NUM_THREADS=2 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=2 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
OMP_NUM_THREADS=2 mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
echo "$ ---"

echo "$ mpiX2"
mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
mpirun --mca btl tcp,self -np $NSLOTS ./bin/pdpjes ${DATASET}
