#!/bin/sh

#$ -S /bin/bash
#$ -cwd
#$ -e ./dist/
#$ -o ./dist/
#$ -pe ompi 1

DATASET="test/fixtures/final*.txt"

echo "$ nompi4"
OMP_NUM_THREADS=4 ./bin/pdpjes --nompi ${DATASET}
OMP_NUM_THREADS=4 ./bin/pdpjes --nompi ${DATASET}
OMP_NUM_THREADS=4 ./bin/pdpjes --nompi ${DATASET}
echo "$ ---"